name: demo_local_notification


description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^19.5.0
  path_provider: ^2.1.5
  timezone: ^0.10.1
  android_alarm_manager_plus: ^5.0.0
  fluttertoast: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0
  drift_dev: ^2.28.3
  build_runner: ^2.8.0


flutter:

  uses-material-design: true


